/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package majorprogram2;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import static java.lang.System.exit;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;


/**
 *
 * @author shayla
 */
public class Menu extends javax.swing.JFrame {
    private MowerWareHouse list;
    private int indicator;
    private String indicate;
    /**
     * Creates new form Menu
     */
    public Menu() {
        list = new MowerWareHouse();
        initComponents();
        indicator = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testforIndicator = new javax.swing.JScrollPane();
        testArea = new javax.swing.JTextArea();
        viewPanel = new javax.swing.JPanel();
        lawnMowerLabel = new javax.swing.JLabel();
        commericalMowerLabel = new javax.swing.JLabel();
        gasPoweredMowerLabel = new javax.swing.JLabel();
        pushReelMowerLabel = new javax.swing.JLabel();
        lmPropButton = new javax.swing.JButton();
        cmPropButton = new javax.swing.JButton();
        gpmPropButton = new javax.swing.JButton();
        prmPropButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        MenuLabel = new javax.swing.JLabel();
        viewWindowLabel = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        mowerComboBox = new javax.swing.JComboBox<>();
        typeOfMowerLabel = new javax.swing.JLabel();
        manuLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        snLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hpLabel = new javax.swing.JLabel();
        cylLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        deckWidthLabel = new javax.swing.JLabel();
        operatingLabel = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        manu1TextField = new javax.swing.JTextField();
        snTextField = new javax.swing.JTextField();
        manu2TextField = new javax.swing.JTextField();
        hpTextField = new javax.swing.JTextField();
        cylTextField = new javax.swing.JTextField();
        modelTextField1 = new javax.swing.JTextField();
        dwTextField = new javax.swing.JTextField();
        ztrLabel = new javax.swing.JLabel();
        ohTextField = new javax.swing.JTextField();
        ztrTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        cwlabel = new javax.swing.JLabel();
        cwTextField = new javax.swing.JTextField();
        wdLabel = new javax.swing.JLabel();
        wdTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        spTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nwTextField = new javax.swing.JTextField();
        addWindowLabel = new javax.swing.JLabel();
        loadButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        testArea.setColumns(20);
        testArea.setRows(5);
        testforIndicator.setViewportView(testArea);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lawnMowerLabel.setText("LawnTractorMower");

        commericalMowerLabel.setText("CommercialMower");

        gasPoweredMowerLabel.setText("GasPoweredMower");

        pushReelMowerLabel.setText("PushReelMower");

        lmPropButton.setText("LTM Properties");
        lmPropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lmPropButtonActionPerformed(evt);
            }
        });

        cmPropButton.setText("CM Properties");
        cmPropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmPropButtonActionPerformed(evt);
            }
        });

        gpmPropButton.setText("GPM Properties");
        gpmPropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpmPropButtonActionPerformed(evt);
            }
        });

        prmPropButton.setText("PRM Properties");
        prmPropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prmPropButtonActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane2.setViewportView(textArea);

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lawnMowerLabel)
                            .addComponent(pushReelMowerLabel)
                            .addComponent(gasPoweredMowerLabel)
                            .addComponent(commericalMowerLabel))
                        .addGap(18, 18, 18)
                        .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmPropButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gpmPropButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lmPropButton)
                            .addComponent(prmPropButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lawnMowerLabel)
                    .addComponent(lmPropButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commericalMowerLabel)
                    .addComponent(cmPropButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gasPoweredMowerLabel)
                    .addComponent(gpmPropButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pushReelMowerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prmPropButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuLabel.setFont(new java.awt.Font("AppleGothic", 1, 48)); // NOI18N
        MenuLabel.setText("Mower Data");

        viewWindowLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        viewWindowLabel.setText("Viewing Window");

        addPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mowerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LawnTractor", "Commerical", "GasPowered", "PushReeal" }));

        typeOfMowerLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        typeOfMowerLabel.setText("Type of Mower");

        manuLabel.setText("Manufacturer1:");

        yearLabel.setText("Year:");

        snLabel.setText("Serial Number: ");

        jLabel3.setText("E- Manufacturer:");

        hpLabel.setText("E- Horse Power:");

        cylLabel.setText("E- Cylinders:");

        modelLabel.setText("Model:");

        deckWidthLabel.setText("Deck Width:");

        operatingLabel.setText("Operating Hours:");

        yearTextField.setText("**int**");
        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });

        manu1TextField.setText("**String**");
        manu1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manu1TextFieldActionPerformed(evt);
            }
        });

        snTextField.setText("**String**");
        snTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snTextFieldActionPerformed(evt);
            }
        });

        manu2TextField.setText("**String**");
        manu2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manu2TextFieldActionPerformed(evt);
            }
        });

        hpTextField.setText("**Double**");
        hpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpTextFieldActionPerformed(evt);
            }
        });

        cylTextField.setText("**int**");
        cylTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cylTextFieldActionPerformed(evt);
            }
        });

        modelTextField1.setText("**String**");
        modelTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextField1ActionPerformed(evt);
            }
        });

        dwTextField.setText("**Double**");
        dwTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dwTextFieldActionPerformed(evt);
            }
        });

        ztrLabel.setText("Zero Turn Radius:");

        ohTextField.setText("**Double**");
        ohTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ohTextFieldActionPerformed(evt);
            }
        });

        ztrTextField.setText("**Boolean**");
        ztrTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ztrTextFieldActionPerformed(evt);
            }
        });

        addButton.setText("Add Mower");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cwlabel.setText("Cut Width:");

        cwTextField.setText("**Double**");
        cwTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cwTextFieldActionPerformed(evt);
            }
        });

        wdLabel.setText("Wheel Diameter:");

        wdTextField.setText("**Double**");
        wdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wdTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Self Propelled:");

        spTextField.setText("**Boolean**");
        spTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Num Wheels:");

        nwTextField.setText("**int**");
        nwTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nwTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(typeOfMowerLabel)
                        .addGap(24, 24, 24)
                        .addComponent(mowerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(manu2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(addPanelLayout.createSequentialGroup()
                                    .addComponent(yearLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(yearTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                                .addGroup(addPanelLayout.createSequentialGroup()
                                    .addComponent(manuLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(manu1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(deckWidthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dwTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(operatingLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ohTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPanelLayout.createSequentialGroup()
                                    .addComponent(hpLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hpTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPanelLayout.createSequentialGroup()
                                    .addComponent(cylLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cylTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPanelLayout.createSequentialGroup()
                                    .addComponent(modelLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(modelTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(addPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPanelLayout.createSequentialGroup()
                                    .addComponent(wdLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(wdTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPanelLayout.createSequentialGroup()
                                    .addComponent(cwlabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cwTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPanelLayout.createSequentialGroup()
                                    .addComponent(ztrLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ztrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(snLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(snTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nwTextField)
                .addGap(25, 25, 25))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mowerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeOfMowerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manuLabel)
                    .addComponent(manu1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snLabel)
                    .addComponent(snTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(manu2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hpLabel)
                    .addComponent(hpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cylLabel)
                    .addComponent(cylTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLabel)
                    .addComponent(modelTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deckWidthLabel)
                    .addComponent(dwTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operatingLabel)
                    .addComponent(ohTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ztrLabel)
                    .addComponent(ztrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cwlabel)
                    .addComponent(cwTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wdLabel)
                    .addComponent(wdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nwTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        addWindowLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        addWindowLabel.setText("Add Window");

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(MenuLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(addWindowLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(viewWindowLabel)
                        .addGap(232, 232, 232))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(viewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewWindowLabel)
                    .addComponent(addWindowLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lmPropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lmPropButtonActionPerformed
          String empty = "";
          textArea.setText(empty);
          textArea.setText(list.LTtoString());
 
    }//GEN-LAST:event_lmPropButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
            indicator = 0;
            indicate = "0";
            testArea.setText(indicate);
            JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            int returnValue = jfc.showSaveDialog(null);            
            File selectedFile = jfc.getSelectedFile();
//            System.out.println(selectedFile.getAbsolutePath());
             try{
            PrintWriter output = new PrintWriter(selectedFile);
            output.println(list.toString());
            output.close();

            }catch(FileNotFoundException ex) {
            System.err.println("couldnt find the file buddy");
            System.exit(-1);        
            }  
             
            JOptionPane.showMessageDialog(rootPane, "You just saved the file!");

    }//GEN-LAST:event_saveButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        if (indicator == 1){
            //do the save thing again
            JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            int returnValue = jfc.showSaveDialog(null);            
            File selectedFile = jfc.getSelectedFile();
//            System.out.println(selectedFile.getAbsolutePath());
             try{
            PrintWriter output = new PrintWriter(selectedFile);
            output.println(list.toString());
            output.close();
            indicator = 0;
            indicate = "0";
            testArea.setText(indicate);
            
            }catch(FileNotFoundException ex) {
            System.err.println("couldnt find the file buddy");
            System.exit(-1);        
            }  
             
            JOptionPane.showMessageDialog(rootPane, "You just saved the file!");
            
        }else{
        exit(-1);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void cmPropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmPropButtonActionPerformed
          String empty = "";
          textArea.setText(empty);
          textArea.setText(list.CtoString());
    }//GEN-LAST:event_cmPropButtonActionPerformed

    private void gpmPropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpmPropButtonActionPerformed
          String empty = "";
          textArea.setText(empty);
          textArea.setText(list.GSPtoString());
    }//GEN-LAST:event_gpmPropButtonActionPerformed

    private void prmPropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prmPropButtonActionPerformed
          String empty = "";
          textArea.setText(empty);
          textArea.setText(list.PRtoString());
    }//GEN-LAST:event_prmPropButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
            JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            int returnValue = jfc.showOpenDialog(null);  
            list.readMowerData("input.txt");
            //textArea.setText(list.toString());
            File selectedFile = jfc.getSelectedFile();
            System.out.println(selectedFile.getAbsolutePath());
            
            indicator = 1;
            indicate = "1";
            testArea.setText(indicate);
            

    }//GEN-LAST:event_loadButtonActionPerformed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void manu1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manu1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manu1TextFieldActionPerformed

    private void snTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snTextFieldActionPerformed

    private void manu2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manu2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manu2TextFieldActionPerformed

    private void hpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hpTextFieldActionPerformed

    private void cylTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cylTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cylTextFieldActionPerformed

    private void modelTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextField1ActionPerformed

    private void dwTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dwTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dwTextFieldActionPerformed

    private void ohTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ohTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ohTextFieldActionPerformed

    private void ztrTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ztrTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ztrTextFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        if (mowerComboBox.getSelectedIndex() == 0) { //lawntractor mower
            LawnTractor lt = new LawnTractor();
            lt.setManufacturer(manu1TextField.getText());
            lt.setYear(Integer.parseInt(yearTextField.getText()));
            lt.setSerialNumber(snTextField.getText());
            Engine e = new Engine();
            e.setManufacturer(manu2TextField.getText());
            e.setHorsePower(Double.parseDouble(hpTextField.getText()));
            e.setCylinders(Integer.parseInt(cylTextField.getText())); 
            lt.setEngine(e);
            lt.setModel(modelTextField1.getText());
            lt.setDeckWidth(Double.parseDouble(dwTextField.getText()));
            list.addMower(lt);
            list.addLTMower(lt);
        } else if (mowerComboBox.getSelectedIndex() == 1){ //commerical mower
            CommericalMower cm = new CommericalMower();
            cm.setManufacturer(manu1TextField.getText());
            cm.setYear(Integer.parseInt(yearTextField.getText()));
            cm.setSerialNumber(snTextField.getText());
            Engine e = new Engine();
            e.setManufacturer(manu2TextField.getText());
            e.setHorsePower(Double.parseDouble(hpTextField.getText()));
            e.setCylinders(Integer.parseInt(cylTextField.getText())); 
            cm.setEngine(e);
            cm.setModel(modelTextField1.getText());
            cm.setDeckWidth(Double.parseDouble(dwTextField.getText()));
            cm.setOperatingHours(Double.parseDouble(ohTextField.getText()));
            cm.setZeroTurnRadius(Boolean.parseBoolean(ztrTextField.getText()));
            list.addMower(cm);
            list.addCMower(cm);
        } else if (mowerComboBox.getSelectedIndex() == 2) { //Gas Powered Mower
            GasPoweredMower gpm = new GasPoweredMower();
            gpm.setManufacturer(manu1TextField.getText());
            gpm.setYear(Integer.parseInt(yearTextField.getText()));
            gpm.setSerialNumber(snTextField.getText());
            gpm.setCutWidth(Double.parseDouble(dwTextField.getText()));
            gpm.setWheelDiameter(Double.parseDouble(wdTextField.getText()));
            Engine e = new Engine();
            e.setManufacturer(manu2TextField.getText());
            e.setHorsePower(Double.parseDouble(hpTextField.getText()));
            e.setCylinders(Integer.parseInt(cylTextField.getText())); 
            gpm.setEngine(e);
            gpm.setSelfPropelled(Boolean.parseBoolean(spTextField.getText()));
            list.addMower(gpm);
            list.addGSPMower(gpm);
        } else if (mowerComboBox.getSelectedIndex() == 3) { //Push Reel Mower
            PushReelMower pr = new PushReelMower();
            pr.setManufacturer(manu1TextField.getText());
            pr.setYear(Integer.parseInt(yearTextField.getText()));
            pr.setSerialNumber(snTextField.getText());
            pr.setCutWidth(Double.parseDouble(dwTextField.getText()));
            pr.setWheelDiameter(Double.parseDouble(wdTextField.getText()));
            pr.setNumWheels(Integer.parseInt(nwTextField.getText()));
            list.addMower(pr);
            list.addPRMower(pr);
        }
        indicator = 1;
        indicate = "1";
        testArea.setText(indicate);
                
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void cwTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cwTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cwTextFieldActionPerformed

    private void wdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wdTextFieldActionPerformed

    private void spTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spTextFieldActionPerformed

    private void nwTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nwTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nwTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Menu().setVisible(true);
            }
        });
    }
    
    public void Menu(MowerWareHouse mwh) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addPanel;
    private javax.swing.JLabel addWindowLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton cmPropButton;
    private javax.swing.JLabel commericalMowerLabel;
    private javax.swing.JTextField cwTextField;
    private javax.swing.JLabel cwlabel;
    private javax.swing.JLabel cylLabel;
    private javax.swing.JTextField cylTextField;
    private javax.swing.JLabel deckWidthLabel;
    private javax.swing.JTextField dwTextField;
    private javax.swing.JLabel gasPoweredMowerLabel;
    private javax.swing.JButton gpmPropButton;
    private javax.swing.JLabel hpLabel;
    private javax.swing.JTextField hpTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lawnMowerLabel;
    private javax.swing.JButton lmPropButton;
    private javax.swing.JButton loadButton;
    private javax.swing.JTextField manu1TextField;
    private javax.swing.JTextField manu2TextField;
    private javax.swing.JLabel manuLabel;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField1;
    private javax.swing.JComboBox<String> mowerComboBox;
    private javax.swing.JTextField nwTextField;
    private javax.swing.JTextField ohTextField;
    private javax.swing.JLabel operatingLabel;
    private javax.swing.JButton prmPropButton;
    private javax.swing.JLabel pushReelMowerLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel snLabel;
    private javax.swing.JTextField snTextField;
    private javax.swing.JTextField spTextField;
    private javax.swing.JTextArea testArea;
    private javax.swing.JScrollPane testforIndicator;
    private javax.swing.JTextArea textArea;
    private javax.swing.JLabel typeOfMowerLabel;
    private javax.swing.JPanel viewPanel;
    private javax.swing.JLabel viewWindowLabel;
    private javax.swing.JLabel wdLabel;
    private javax.swing.JTextField wdTextField;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    private javax.swing.JLabel ztrLabel;
    private javax.swing.JTextField ztrTextField;
    // End of variables declaration//GEN-END:variables
}
